image: ruby:2.4.2

stages:
  - build
  - test
  - publish
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

# before_script:
# - cd reddit
# - bundle install

# build_job:
#   stage: build
#   script:
#     - echo 'Building'

# test_unit_job:
#   stage: test
#   services:
#     - mongo:latest
#   before_script:
#     - cd reddit
#     - bundle install
#   script:
#     - ruby simpletest.rb

# test_integration_job:
#   stage: test
#   script:
#     - echo 'Testing 2'

publish:
  image: docker:latest
  stage: publish
  services:
    - name: docker:18-dind
      entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
  variables:
    DOCKER_DAEMON_OPTIONS: "--insecure-registry=${CI_REGISTRY} --tls=false"
  before_script:
    - echo $DAEMON_CONFIG
    - echo $TAG_LATEST
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_BUILD_TOKEN
    - echo $CI_REGISTRY
  script:
    - mkdir /etc/docker &&  cat "$DAEMON_CONFIG" > /etc/docker/daemon.json
    - export DOCKER_TLS_CERTDIR=
    - cd reddit
    - docker build -t "$TAG_LATEST" .
    # - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push "$TAG_LATEST"

deploy_dev_job:
  image: alpine:latest
  stage: review
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    # - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_LATEST"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f mongo || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f reddit || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker network rm -f reddit || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker network create reddit || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d --network=reddit -p 27017:27017 --name mongo mongo:latest"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d --network=reddit -p 9292:9292 -e DATABASE_URL=mongo:27017 --name reddit $TAG_LATEST"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$SERVER_IP:9292
  only:
  - branches
  except:
  - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
