---
- name: Create directories
  tags: server
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs

- name: Copy docker-compose config
  tags: server
  template:
    src: docker-compose.yml.j2
    dest: /srv/gitlab/docker-compose.yml

- name: Run docker-compose
  tags: server
  docker_compose:
    project_src: /srv/gitlab
