---
- name: Create users
  hosts: all
  become: true

  tasks:
    - name: create the kube user account
      user:
        name: kube
        groups:
          - sudo
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash

    - name: allow 'kube' to use sudo without password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      authorized_key:
        user: kube
        key: "{{item}}"
      with_file:
        - ~/.ssh/appuser.pub
