---
- name: Install Docker container runtime
  hosts: all
  become: true

  tasks:
    - name: Add Docker signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker

    - name: Install Docker package
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Configure Docker daemon
      copy:
        src: ../files/docker-daemon.json
        dest: /etc/docker/daemon.json
      notify: restart docker


  handlers:
    - name: restart docker
      become: true
      service: name=docker state=restarted
