apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: ui
      name: ui
    spec:
      type: NodePort
      ports:
        - name: "9292"
          port: 9292
          targetPort: 9292
      selector:
        io.kompose.service: ui
    status:
      loadBalancer: {}

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: post
      name: post
    spec:
      ports:
        - name: "5000"
          port: 5000
          targetPort: 5000
      selector:
        io.kompose.service: post
    status:
      loadBalancer: {}

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: comment
      name: comment
    spec:
      ports:
        - name: "9292"
          port: 9292
          targetPort: 9292
      selector:
        io.kompose.service: comment
    status:
      loadBalancer: {}

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: mongo-db
      name: mongo-db
    spec:
      ports:
        - name: "27017"
          port: 27017
          targetPort: 27017
      selector:
        io.kompose.service: mongo-db
    status:
      loadBalancer: {}

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: comment
      name: comment
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: comment
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: comment
        spec:
          containers:
            - image: andrewmachine/comment
              name: comment
              resources: {}
              env:
                - name: COMMENT_DATABASE_HOST
                  value: mongo-db
          restartPolicy: Always
    status: {}

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: mongo-db
      name: mongo-db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: mongo-db
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: mongo-db
        spec:
          containers:
            - image: mongo:latest
              name: mongo-db
              resources: {}
              volumeMounts:
                - mountPath: /data/db
                  name: mongo-db
          restartPolicy: Always
          volumes:
            - name: mongo-db
              persistentVolumeClaim:
                claimName: mongo-db
    status: {}

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        io.kompose.service: mongo-db
      name: mongo-db
    spec:
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: post
      name: post
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: post
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: post
        spec:
          containers:
            - image: andrewmachine/post
              name: post
              resources: {}
              env:
                - name: POST_DATABASE_HOST
                  value: mongo-db
          restartPolicy: Always
    status: {}

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: ui
      name: ui
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: ui
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: ui
        spec:
          containers:
            - image: andrewmachine/ui
              name: ui
              ports:
                - containerPort: 9292
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}
