version: '3.3'
services:
  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${IMAGE_USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_EXTERNAL_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${IMAGE_USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
    links:
      - mongo_db:post_db
  comment:
    build: ./comment
    image: ${IMAGE_USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    links:
      - mongo_db:comment_db

volumes:
  mongo_db:

networks:
  back_net:
    driver: bridge
  front_net:
    driver: bridge
