version: '3.3'
services:

  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_db:/data/db
    networks:
      - back_net

  ui:
    build: ./ui
    image: ${IMAGE_USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_EXTERNAL_PORT}:9292/tcp
    networks:
      - front_net

  post:
    build: ./post-py
    image: ${IMAGE_USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
    links:
      - mongo_db:post_db

  comment:
    build: ./comment
    image: ${IMAGE_USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    links:
      - mongo_db:comment_db

  prometheus:
    image: ${IMAGE_USERNAME}/prometheus:${PROMETHEUS_VERISION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - '9115:9115'
    networks:
      - back_net

  node-exporter:
    image: prom/node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongo-exporter:
    image: percona/mongodb_exporter:0.20
    ports:
      - '9216:9216'
    command:
      - '--mongodb.uri=mongodb://mongo_db:27017'
    networks:
      - back_net

volumes:
  mongo_db:
  prometheus_data:

networks:
  back_net:
    driver: bridge
  front_net:
    driver: bridge
