---
- name: Install GitLab usnig Omnibus
  hosts: all
  become: true
  tags: gitlab

  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /srv/gitlab/config
        - /srv/gitlab/data
        - /srv/gitlab/logs

    - name: Copy docker-compose config
      copy:
        src: ../files/docker-compose.yml
        dest: /srv/gitlab/docker-compose.yml

    - name: Run docker-compose
      docker_compose:
        project_src: /srv/gitlab
