---
- name: Install Docker
  hosts: all
  become: true
  tags: install

  tasks:
    - name: Install utility packages
      apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip

    - name: Add signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker.list

    - name: Install Docker package
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - containerd.io

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Enable Docker service
      service:
        name: docker
        enabled: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
